access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY

language: generic

sudo: required  #need super user to execute the build

services:
  - docker #automatically install docker.  

before_install:
  - docker build -t tracyalbers/docker-react -f Dockerfile.dev . #use the current directory and look for the .dev file (-f)

script:
  - docker run -e CI=true tracyalbers/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-714107542275"
  bucket_path: "docker"
  on:
    branch: master