version: '3'
services:
  web:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '80:80'
    volumes:
      - /app/node_modules
      - .:/app
  tests: #second service for testing, no ports for testing
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules  #set up a placeholder and don't override
      - .:/app #pull in the current working directory
    command: ['npm', 'run', 'test'] #override the command 
